/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    MemorySizeChip: typeof import('./components/MemorySizeChip.vue')['default']
    RecentTasks: typeof import('./components/RecentTasks.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScoreProgress: typeof import('./components/ScoreProgress.vue')['default']
    TaskCard: typeof import('./components/TaskCard.vue')['default']
    TaskForm: typeof import('./components/TaskForm.vue')['default']
    TaskResultGrid: typeof import('./components/TaskResultGrid.vue')['default']
    TimeChip: typeof import('./components/TimeChip.vue')['default']
    VApp: typeof import('vuetify/components')['VApp']
    VBtn: typeof import('vuetify/components')['VBtn']
    VBtnToggle: typeof import('vuetify/components')['VBtnToggle']
    VCard: typeof import('vuetify/components')['VCard']
    VCardActions: typeof import('vuetify/components')['VCardActions']
    VCardSubtitle: typeof import('vuetify/components')['VCardSubtitle']
    VCardText: typeof import('vuetify/components')['VCardText']
    VCardTitle: typeof import('vuetify/components')['VCardTitle']
    VCheckbox: typeof import('vuetify/components')['VCheckbox']
    VChip: typeof import('vuetify/components')['VChip']
    VCol: typeof import('vuetify/components')['VCol']
    VCombobox: typeof import('vuetify/components')['VCombobox']
    VContainer: typeof import('vuetify/components')['VContainer']
    VDefaultsProvider: typeof import('vuetify/components')['VDefaultsProvider']
    VDialog: typeof import('vuetify/components')['VDialog']
    VExpandTransition: typeof import('vuetify/components')['VExpandTransition']
    VFooter: typeof import('vuetify/components')['VFooter']
    VForm: typeof import('vuetify/components')['VForm']
    VIcon: typeof import('vuetify/components')['VIcon']
    VMain: typeof import('vuetify/components')['VMain']
    VProgressCircular: typeof import('vuetify/components')['VProgressCircular']
    VResponsive: typeof import('vuetify/components')['VResponsive']
    VRow: typeof import('vuetify/components')['VRow']
    VSelect: typeof import('vuetify/components')['VSelect']
    VSpacer: typeof import('vuetify/components')['VSpacer']
    VTable: typeof import('vuetify/components')['VTable']
    VTextField: typeof import('vuetify/components')['VTextField']
  }
}
