/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    RecentTasks: typeof import('./components/RecentTasks.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScoreProgress: typeof import('./components/ScoreProgress.vue')['default']
    VApp: typeof import('vuetify/components')['VApp']
    VCard: typeof import('vuetify/components')['VCard']
    VCardActions: typeof import('vuetify/components')['VCardActions']
    VCardText: typeof import('vuetify/components')['VCardText']
    VCol: typeof import('vuetify/components')['VCol']
    VForm: typeof import('vuetify/components')['VForm']
    VIcon: typeof import('vuetify/components')['VIcon']
    VMain: typeof import('vuetify/components')['VMain']
    VProgressCircular: typeof import('vuetify/components')['VProgressCircular']
    VResponsive: typeof import('vuetify/components')['VResponsive']
    VRow: typeof import('vuetify/components')['VRow']
  }
}
